

POST {{baseUrl}}/auth/sign-up
Content-Type: application/json

{
    "name": "gk-elite-ceo",
    "email": "gkeliteceo@gmail.com",
    "password" : "123456",
    "organization":"GK-Elite",
    "role":"CEO"
}

###
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "password" : "123456",
    "email": "gkeliteceo@gmail.com"
}

###
GET {{baseUrl}}/auth/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YzQxNWMxMGExODdhMzY5Y2IxMWZmYSIsImVtYWlsIjoiZ2tlbGl0ZWNlb0BnbWFpbC5jb20iLCJpYXQiOjE3NTc2ODExMDJ9.TuV5VlCsKbmQTZsH8Ssp2Jy7U5ydMwGDJ6trvLvroyw

###
POST {{baseUrl}}/auth/add-hr
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YzQxNWMxMGExODdhMzY5Y2IxMWZmYSIsImVtYWlsIjoiZ2tlbGl0ZWNlb0BnbWFpbC5jb20iLCJpYXQiOjE3NTc2ODExMDJ9.TuV5VlCsKbmQTZsH8Ssp2Jy7U5ydMwGDJ6trvLvroyw

{
    "name": "gk-elite-hr",
    "email": "gkelitehr@gmail.com",
    "password" : "123456",
    "role":"Hr"
}